# Generated by Django 5.2.3 on 2025-07-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_note_content_note_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص التحذير الأمني')),
            ],
        ),
    ]
