# Generated by Django 5.2.3 on 2025-07-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_securitywarning'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='issuer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الجهة المصدرة'),
        ),
        migrations.AddField(
            model_name='note',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='التوقيع'),
        ),
        migrations.AddField(
            model_name='note',
            name='stamp',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='الختم'),
        ),
    ]
