# Generated by Django 5.2.3 on 2025-07-02 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_issuer_name_note_signature_note_stamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية'),
        ),
        migrations.AddField(
            model_name='note',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='مؤرشف'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employee', 'موظف'), ('viewer', 'عرض فقط'), ('reader', 'قراءة'), ('supervisor', 'مشرف رئيسي'), ('admin', 'مدير النظام')], default='viewer', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
