# Generated by Django 5.2.3 on 2025-07-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_expiry_date_note_is_archived_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الوسم')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='محتوى الوثيقة'),
        ),
        migrations.AddField(
            model_name='note',
            name='doc_type',
            field=models.CharField(choices=[('administrative', 'أمر إداري'), ('official', 'كتاب رسمي'), ('circular', 'تعميم')], default='official', max_length=20, verbose_name='نوع الوثيقة'),
        ),
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='ملف مرفق (PDF)'),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='أرشفة'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان الوثيقة'),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, to='notes.tag', verbose_name='الوسوم'),
        ),
    ]
