# Generated by Django 5.2.3 on 2025-07-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_note_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='تم الحذف؟'),
        ),
    ]
