# Generated by Django 5.2.3 on 2025-07-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_note_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='direction',
            field=models.CharField(choices=[('outgoing', 'صادرة'), ('incoming', 'واردة')], default='outgoing', max_length=10, verbose_name='جهة الوثيقة'),
        ),
    ]
