# Generated by Django 5.2.3 on 2025-07-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_attachment_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الجهة المستقبلة'),
        ),
    ]
