# Generated by Django 5.2.3 on 2025-07-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_note_recipient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'موظف'), ('normal', 'مستخدم عادي'), ('viewer', 'عرض فقط'), ('reader', 'قراءة'), ('supervisor', 'مشرف رئيسي'), ('admin', 'مدير النظام')], default='viewer', max_length=20),
        ),
    ]
