# Generated by Django 5.2.3 on 2025-07-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='importance',
            field=models.CharField(choices=[('normal', 'عادي'), ('important', 'مهم'), ('urgent', 'عاجل')], default='normal', max_length=20, verbose_name='درجة الأهمية'),
        ),
    ]
