# Generated by Django 5.2.3 on 2025-07-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_note_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط الملف المرفوع'),
        ),
    ]
