# Generated by Django 5.2.3 on 2025-07-27 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_remove_accessnotification_user_agent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file_for_user',
            field=models.ForeignKey(blank=True, help_text='الملف يظهر فقط لهذا المستخدم إذا تم اختياره', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protected_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='file_login_only',
            field=models.BooleanField(default=False, verbose_name='الملف المرفق محمي (يظهر فقط بعد تسجيل الدخول)'),
        ),
        migrations.AddField(
            model_name='note',
            name='is_private',
            field=models.BooleanField(default=False, help_text='إذا كانت الوثيقة خاصة، لا يمكن لأي مستخدم آخر رؤيتها حتى عبر QR', verbose_name='وثيقة خاصة (يظهرها فقط صاحبها)'),
        ),
        migrations.AddField(
            model_name='note',
            name='login_only',
            field=models.BooleanField(default=False, help_text='لا يمكن لأي زائر أو غير مسجل الدخول رؤيتها حتى عبر QR', verbose_name='تظهر فقط بعد تسجيل الدخول'),
        ),
    ]
