# Generated by Django 5.2.3 on 2025-07-28 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0020_userprofile_activation_token_newscomment_newslike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('FIELD_UPDATE', 'تحديث حقل'), ('FILE_UPLOAD', 'رفع ملف'), ('FILE_DELETE', 'حذف ملف'), ('STATUS_CHANGE', 'تغيير حالة'), ('PERMISSION_CHANGE', 'تغيير صلاحية'), ('METADATA_UPDATE', 'تحديث بيانات وصفية')], max_length=20)),
                ('field_name', models.CharField(blank=True, help_text='اسم الحقل المتغير', max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, help_text='القيمة القديمة', null=True)),
                ('new_value', models.TextField(blank=True, help_text='القيمة الجديدة', null=True)),
                ('change_reason', models.TextField(blank=True, help_text='سبب التغيير', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='notes.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'إنشاء'), ('READ', 'قراءة'), ('UPDATE', 'تحديث'), ('DELETE', 'حذف'), ('LOGIN', 'تسجيل دخول'), ('LOGOUT', 'تسجيل خروج'), ('DOWNLOAD', 'تحميل'), ('SHARE', 'مشاركة'), ('ARCHIVE', 'أرشفة'), ('RESTORE', 'استرجاع'), ('ROLE_CHANGE', 'تغيير صلاحية'), ('PASSWORD_CHANGE', 'تغيير كلمة السر'), ('SETTINGS_CHANGE', 'تغيير إعدادات')], max_length=20)),
                ('resource_type', models.CharField(help_text='نوع المورد (وثيقة، مستخدم، إلخ)', max_length=50)),
                ('resource_id', models.CharField(blank=True, help_text='معرف المورد', max_length=100, null=True)),
                ('resource_name', models.CharField(blank=True, help_text='اسم المورد', max_length=255, null=True)),
                ('description', models.TextField(help_text='وصف مفصل للعملية')),
                ('old_values', models.JSONField(blank=True, help_text='القيم القديمة', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='القيم الجديدة', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('severity', models.CharField(choices=[('LOW', 'منخفض'), ('MEDIUM', 'متوسط'), ('HIGH', 'عالي'), ('CRITICAL', 'حرج')], default='LOW', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True, help_text='هل نجحت العملية؟')),
                ('error_message', models.TextField(blank=True, help_text='رسالة الخطأ إن وجدت', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='notes_audit_user_id_bfac4e_idx'), models.Index(fields=['action', '-timestamp'], name='notes_audit_action_a83e07_idx'), models.Index(fields=['resource_type', '-timestamp'], name='notes_audit_resourc_b7f4a3_idx'), models.Index(fields=['severity', '-timestamp'], name='notes_audit_severit_891712_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('SUSPICIOUS_LOGIN', 'تسجيل دخول مشبوه'), ('MULTIPLE_FAILED_LOGINS', 'محاولات دخول فاشلة متعددة'), ('UNAUTHORIZED_ACCESS', 'وصول غير مخول'), ('DATA_BREACH_ATTEMPT', 'محاولة اختراق بيانات'), ('UNUSUAL_ACTIVITY', 'نشاط غير عادي'), ('PERMISSION_ESCALATION', 'محاولة رفع صلاحيات'), ('BULK_DOWNLOAD', 'تحميل كمي مشبوه'), ('IP_BLACKLIST', 'IP في القائمة السوداء')], max_length=30)),
                ('risk_level', models.CharField(choices=[('LOW', 'منخفض'), ('MEDIUM', 'متوسط'), ('HIGH', 'عالي'), ('CRITICAL', 'خطر جداً')], max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('description', models.TextField(help_text='وصف التنبيه')),
                ('details', models.JSONField(blank=True, help_text='تفاصيل إضافية', null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['alert_type', '-timestamp'], name='notes_secur_alert_t_ebf26b_idx'), models.Index(fields=['risk_level', '-timestamp'], name='notes_secur_risk_le_777215_idx'), models.Index(fields=['is_resolved', '-timestamp'], name='notes_secur_is_reso_5d4756_idx')],
            },
        ),
    ]
