# Generated by Django 5.2.3 on 2025-07-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0021_documentchangelog_auditlog_securityalert'),
    ]

    operations = [
    ]
