# Generated by Django 5.2.3 on 2025-07-29 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0022_add_audit_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('documents_created', models.IntegerField(default=0)),
                ('documents_viewed', models.IntegerField(default=0)),
                ('documents_downloaded', models.IntegerField(default=0)),
                ('documents_archived', models.IntegerField(default=0)),
                ('users_registered', models.IntegerField(default=0)),
                ('users_active', models.IntegerField(default=0)),
                ('user_logins', models.IntegerField(default=0)),
                ('news_created', models.IntegerField(default=0)),
                ('news_views', models.IntegerField(default=0)),
                ('news_likes', models.IntegerField(default=0)),
                ('news_comments', models.IntegerField(default=0)),
                ('security_alerts', models.IntegerField(default=0)),
                ('failed_logins', models.IntegerField(default=0)),
                ('suspicious_activities', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إحصائيات يومية',
                'verbose_name_plural': 'الإحصائيات اليومية',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(help_text='حجم الملف بالبايت')),
                ('file_type', models.CharField(choices=[('document', 'وثيقة'), ('image', 'صورة'), ('pdf', 'PDF'), ('office', 'ملف مكتبي'), ('other', 'أخرى')], max_length=20)),
                ('mime_type', models.CharField(max_length=100)),
                ('is_safe', models.BooleanField(default=True)),
                ('virus_scan_result', models.CharField(blank=True, max_length=50, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='العملية')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('action_type', models.CharField(choices=[('document', 'وثيقة'), ('news', 'خبر'), ('user', 'مستخدم'), ('system', 'نظام'), ('auth', 'مصادقة'), ('admin', 'إداري'), ('security', 'أمني'), ('general', 'عام')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_public', models.BooleanField(default=True, verbose_name='عام (يظهر للجميع)')),
                ('is_important', models.BooleanField(default=False, verbose_name='مهم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='notes_activ_created_b5ff62_idx'), models.Index(fields=['user', '-created_at'], name='notes_activ_user_id_b03189_idx'), models.Index(fields=['action_type', '-created_at'], name='notes_activ_action__4178b5_idx'), models.Index(fields=['is_public', '-created_at'], name='notes_activ_is_publ_6d8ab0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('type', models.CharField(choices=[('document', 'وثيقة'), ('news', 'خبر'), ('user', 'مستخدم'), ('system', 'نظام'), ('security', 'أمني'), ('reminder', 'تذكير')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_email_sent', models.BooleanField(default=False, verbose_name='تم إرسال بريد إلكتروني')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('normal', 'عادي'), ('high', 'عالي'), ('urgent', 'عاجل')], default='normal', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notes_notif_user_id_f30f06_idx'), models.Index(fields=['user', 'is_read'], name='notes_notif_user_id_b94d65_idx'), models.Index(fields=['type', '-created_at'], name='notes_notif_type_23b177_idx')],
            },
        ),
    ]
